blank_issues_enabled: false
contact_links:
- name: ğŸ’¬ Community Forum
  url: https://forums.xaisyndicate.co.id
  about: Ask the community for help on our forum.
- name: â” Support Question
  url: https://xsimarket.uvdesk.com/en/customer/create-ticket/
  about: This repository is only for reporting bugs or feature requests, please create a support ticket if you need any assistance from our team.
